# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --no-restore --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet test --no-restore $(buildConfiguration)
  displayName: 'dotnet test'

- script: dotnet pack ./Dotnet.Rename/Dotnet.Rename.csproj --no-restore --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack'

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'nuget'
